version: '3'
services:

  divvaipg_dev:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=divvai
        - POSTGRES_PASSWORD=divvai
        - POSTGRES_DB=divvai
      volumes:
        - ./postgres-data/postgres:/var/lib/postgresql/data
      expose:
        - "5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
