version: '3'
services:

  splitter_db:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./postgres-data/postgres:/var/lib/postgresql/data
      networks:
        db_nw

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw

  splitter:
    restart: always
    image: "splitter/splitter:latest"
    ports:
      - "5000:5000"
    env_file:
      - ./env-files/dev-env-file
    volumes:
      - ../migrations/versions/:/app/migrations/versions/
    links:
      - "splitter_db"
    depends_on:
      - "splitter_db"
    networks:
      - web_nw
      - db_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
